### ISSUE TITLE
List Materi HTML

### ISSUE THREAD

**Issue by DevinWinando** [bellshade/HTML-CSS#203]
### Status

| Emoji | Deskripsi |
| :--: | :--: |
| 🏃 | Sedang dikerjakan |
| 👀 | Sedang direview |

### Daftar-daftar materi HTML yang belum diselesaikan.

- [x] 016 HTML Picture (@Aclaputra) #229 
- [x] 021 HTML Id (@DevinWinando) #216 
- [x] 023 HTML Script (@DevinWinando) #216 
- [x] 025 HTML Head (@DevinWinando) #221 
- [x] 026 HTML Link (@kingramzy) #226 
- [x] 028 HTML Base (@manh21) #268 
- [x] 033 HTML Symbols (@manh21) #266
- [x] 034 HTML Emojis (@Fanreza) #252  
- [ ] 035 HTML Forms (kurang form attribute dan materi input type harusnya tidak perlu dimasukkan disini )
- [x] 037 HTML Label (@manh21) #269
- [x] 038 HTML Select (@pamela-sarnia) #261 
- [x] 039 HTML Input Attributes (@azizarizaldi) #280 
- [x] 041 HTML Textarea
- [x] 044 HTML SVG 
- [x] 045 HTML Multimedia
- [x] 046 HTML Figure (@fadelun) #263 

Jika ingin menambahkan materi yang ada pada list ini, silakan beri komentar pada issue ini agar tidak bentrok dengan yang lainnya saat mengerjakan materi tersebut. Diingatkan kembali untuk membaca [panduan kontribusi](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) sebelum berkontribusi.

Jika ada masalah silahkan didiskusikan di issue ini atau di [discord wpu](https://discord.com/wpu)

**Comment by DevinWinando** [comment]
Saya akan mengerjakan materi 021 HTML Id dan 023 HTML Script

**Comment by Aclaputra** [comment]
Saya akan mengerjakan materi ```016 HTML Picture``` boleh min?

**Comment by DevinWinando** [comment]
> Saya akan mengerjakan materi `016 HTML Picture` boleh min?

Boleh banget kak

**Comment by Aclaputra** [comment]
> > Saya akan mengerjakan materi `016 HTML Picture` boleh min?
> 
> Boleh banget kak

owh baru lihat, kirain ngga boleh wkwk ntar langsung saya buat 👍

**Comment by slowy07** [comment]
@bellshade/htmlcss-team, tambahkan materi link video dari web programming unpas, linking videonya ke dalam markdown untuk sebagai acuan, contoh

```
[materi html image](link_sumber_youtube)
```

**Comment by Fanreza** [comment]
Saya akan mengerjakan HTML Emojis 034

**Comment by pamela-sarnia** [comment]
Saya akan mengerjakan #039 HTML Textarea

**Comment by pamela-sarnia** [comment]
saya akan mengerjakan `038 HTML Select`

**Comment by fadelun** [comment]
Saya akan mengerjakan `046 HTML Figure`

**Comment by fadelun** [comment]
sya akan mengerjakan `045 HTML Multimedia`

**Comment by azizarizaldi** [comment]
halo kak devin boleh saya coba untuk mengerjakan **036 HTML Input Attributes** ?

**Comment by abnvlf** [comment]
> halo kak devin boleh saya coba untuk mengerjakan **036 HTML Input Attributes** ?

silakan kak

**Comment by azizarizaldi** [comment]
oke bang @abnvlf aku langsung fork yaaa ini. thanks!

**Comment by azizarizaldi** [comment]
bang @abnvlf @DevinWinando mau nanya nih, untuk yang **036 HTML Input Attributes**
![image](https://github.com/bellshade/HTML-CSS/assets/43601207/75cd382f-c371-4e5d-862a-0b6d4b6bbd26)

tidak ada directory folder "**036 HTML Input Attributes**", yang ada cuman folder **036 HTML Input Types**:
![image](https://github.com/bellshade/HTML-CSS/assets/43601207/564c87ad-ae75-4658-a915-300ce8e2720e)

jadinya yang **036 HTML Input Attributes** ini akun tambahkan atau aku ganti aja yang **036 HTML Input Types** jadi **036 HTML Input Types** ?

**Comment by abnvlf** [comment]
bisa di 039 dulu kak

**Comment by abnvlf** [comment]
> bang @abnvlf @DevinWinando mau nanya nih, untuk yang **036 HTML Input Attributes**
> 
> ![image](https://user-images.githubusercontent.com/43601207/274160825-75cd382f-c371-4e5d-862a-0b6d4b6bbd26.png)
> 
> tidak ada directory folder "**036 HTML Input Attributes**", yang ada cuman folder **036 HTML Input Types**:
> 
> ![image](https://user-images.githubusercontent.com/43601207/274161049-564c87ad-ae75-4658-a915-300ce8e2720e.png)
> 
> jadinya yang **036 HTML Input Attributes** ini akun tambahkan atau aku ganti aja yang **036 HTML Input Types** jadi **036 HTML Input Attributes** ?

bisa di 039 dulu aja kak

**Comment by azizarizaldi** [comment]
siaap @abnvlf aku coba isi di **039** yaa:
jadi -> **039 HTML Input Attributes ?**

**Comment by abnvlf** [comment]
> siaap @abnvlf aku coba isi di **039** yaa: jadi -> **039 HTML Input Attributes ?**

iya

**Comment by cecepfahriazal1997** [comment]
Halo kak @abnvlf @DevinWinando 
mw konfirmasi, untuk 3 materi ini dibawah ini apakah masih kosong ?

 041 HTML Textarea
 044 HTML SVG
 045 HTML Multimedia
 
 saya ingin coba untuk berkontribusi

**Comment by slowy07** [comment]
sudah ada untuk [041](https://github.com/bellshade/HTML-CSS/tree/main/HTML/041%20HTML%20Textarea),[044](https://github.com/bellshade/HTML-CSS/tree/main/HTML/044%20HTML%20Multimedia), dan [045](https://github.com/bellshade/HTML-CSS/tree/main/HTML/045%20HTML%20SVG), untuk yang tidak ada bisa kamu lihat di atas dan bisa membuka sub issue yang baru dan kemudian bisa membuat pull request dengan referensi dari sub issue yang sudah kamu buat sebelumnya, terima kasih 💯

**Comment by cecepfahriazal1997** [comment]
baik kak @slowy07
