### ISSUE TITLE
List Materi CSS

### ISSUE THREAD

**Issue by DevinWinando** [bellshade/HTML-CSS#204]
### Status

| Emoji | Deskripsi |
| :--: | :--: |
| 🏃 | Sedang dikerjakan |
| 👀 | Sedang direview |

### Daftar-daftar materi CSS yang belum diselesaikan.

- [x] 001 CSS Introduction (@abinoval) #214 
- [x] 008 CSS Borders (@MZYXn) #225 
- [x] 020 CSS Google Font (@pamela-sarnia) #260 
- [x] 021 CSS Icons (@pamela-sarnia) #259 
- [x] 022 CSS Lists
- [x] 023 CSS Display (@abinoval) #230 
- [x] 032 CSS Attribute Selector (@naufalf25) #237 
- [ ] 033 CSS Counters (@azizarizaldi )
- [x] 035 CSS Specificity (@sejutaimpian) #287 
- [x] 038 CSS Border Image
- [x] 046 CSS Animation (@syzkii) #265 
- [x] 049 CSS Object Position
- [x] 051 CSS Column
- [ ] 052 CSS Resize

Jika ingin menambahkan materi yang ada pada list ini, silakan beri komentar pada issue ini agar tidak bentrok dengan yang lainnya saat mengerjakan materi tersebut. Diingatkan kembali untuk membaca [panduan kontribusi](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) sebelum berkontribusi.

Jika ada masalah silahkan didiskusikan di issue ini atau di [discord wpu](https://discord.com/wpu)

**Comment by abinoval** [comment]
Saya akan mengerjakan materi `001 CSS Introduction`

**Comment by MZYXn** [comment]
Saya akan mengerjakan materi `008 CSS Borders`

**Comment by syahid246** [comment]
Saya ingin memperbaiki (menambah) pada materi `019 CSS Web Font`, bagaimana contoh membuat _issue_ nya?

**Comment by kingramzy** [comment]
> Saya ingin memperbaiki (menambah) pada materi `019 CSS Web Font`, bagaimana contoh membuat _issue_ nya? Saya sudah membuat commit di [github.com/syahid246/HTML-CSS/commits/main/CSS/019 CSS Web Font](https://github.com/syahid246/HTML-CSS/commits/main/CSS/019%20CSS%20Web%20Font)

ooh silahkan buat issue. klik new issue untuk membuat issue baru

**Comment by aryomuzakki** [comment]
Saya akan mengerjakan materi `035 CSS Specificity`

**Comment by naufalf25** [comment]
Saya akan mengerjakan materi `032 CSS Attribute Selector`

**Comment by pamela-sarnia** [comment]
Saya akan mengerjakan `020 CSS Google Font`

**Comment by pamela-sarnia** [comment]
> Saya akan mengerjakan `020 CSS Google Font`

Saya sudah mengerjakan

**Comment by pamela-sarnia** [comment]
Saya akan mengerjakan `021 CSS Icons`

**Comment by pamela-sarnia** [comment]
> * 022 CSS Lists

Saya sudah mengerjakan

**Comment by pamela-sarnia** [comment]
> Saya akan mengerjakan `021 CSS Icons`

Saya sudah mengerjakan

**Comment by pamela-sarnia** [comment]
Saya akan mengerjakan `022 CSS Lists`

**Comment by fadelun** [comment]
Saya akan mengerjakan 051 `CSS Column`

**Comment by fadelun** [comment]
Saya akan mengerjakan ` 022 CSS Lists
`

**Comment by fadelun** [comment]
Saya akan mengerjakan  `049 CSS Object Position`

**Comment by fadelun** [comment]
Saya akan mengerjakan `038 CSS Border Image`

**Comment by syzkii** [comment]
saya akan mengerjakan `052 CSS Resize`

**Comment by azizarizaldi** [comment]
halo bang @abnvlf untuk materi **033 CSS Counters** boleh aku kerjakan?

**Comment by abnvlf** [comment]
> halo bang @abnvlf untuk materi **033 CSS Counters** boleh aku kerjakan?

silakan

**Comment by azizarizaldi** [comment]
siap bang @abnvlf aku keep yaa

**Comment by azizarizaldi** [comment]
halo bang @abnvlf materi **033 CSS Counters** sudah aku coba tambahkan yaa..

**Comment by cecepfahriazal1997** [comment]
Halo kak @abnvlf boleh kah saya mengerjakan materi **022 CSS Lists** ?

**Comment by GiriDiwa73** [comment]
Saya akan Mengerjakan **035.CSS Specificity**

**Comment by sejutaimpian** [comment]
Saya akan mengerjakan materi `035 CSS Specificity`. Berikan saya waktu selama 7 hari untuk mengerjakan materi ini.
